// Mocks generated by Mockito 5.4.6 from annotations
// in ppplayer/test/persistence_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:ppplayer/core/api/spotify_client.dart' as _i3;
import 'package:ppplayer/core/models/track.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTrack_0 extends _i1.SmartFake implements _i2.Track {
  _FakeTrack_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SpotifyClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpotifyClient extends _i1.Mock implements _i3.SpotifyClient {
  MockSpotifyClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get market =>
      (super.noSuchMethod(
            Invocation.getter(#market),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#market),
            ),
          )
          as String);

  @override
  _i5.Future<Map<String, dynamic>> search(String? query, {int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query], {#limit: limit}),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<_i2.Track>> searchTracks(String? query, {int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#searchTracks, [query], {#limit: limit}),
            returnValue: _i5.Future<List<_i2.Track>>.value(<_i2.Track>[]),
          )
          as _i5.Future<List<_i2.Track>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> searchPlaylists(
    String? query, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchPlaylists, [query], {#limit: limit}),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>> getArtist(String? artistId) =>
      (super.noSuchMethod(
            Invocation.method(#getArtist, [artistId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getMultipleArtists(
    List<String>? ids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMultipleArtists, [ids]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<dynamic>> getArtistTopTracks(String? artistId) =>
      (super.noSuchMethod(
            Invocation.method(#getArtistTopTracks, [artistId]),
            returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<List<dynamic>> getArtistAlbums(
    String? artistId, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getArtistAlbums, [artistId], {#limit: limit}),
            returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<_i2.Track> getTrack(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrack, [trackId]),
            returnValue: _i5.Future<_i2.Track>.value(
              _FakeTrack_0(this, Invocation.method(#getTrack, [trackId])),
            ),
          )
          as _i5.Future<_i2.Track>);

  @override
  _i5.Future<Map<String, dynamic>> getAlbum(String? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbum, [albumId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getMultipleAlbums(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getMultipleAlbums, [ids]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<_i2.Track>> getAlbumTracks(String? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbumTracks, [albumId]),
            returnValue: _i5.Future<List<_i2.Track>>.value(<_i2.Track>[]),
          )
          as _i5.Future<List<_i2.Track>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getNewReleases({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getNewReleases, [], {#limit: limit}),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<_i2.Track>> getRecommendations({
    String? seedTrackId,
    String? seedArtistId,
    String? seedGenres,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendations, [], {
              #seedTrackId: seedTrackId,
              #seedArtistId: seedArtistId,
              #seedGenres: seedGenres,
              #limit: limit,
            }),
            returnValue: _i5.Future<List<_i2.Track>>.value(<_i2.Track>[]),
          )
          as _i5.Future<List<_i2.Track>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getFeaturedPlaylists({
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFeaturedPlaylists, [], {#limit: limit}),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<_i2.Track>> getPlaylistTracks(
    String? playlistId, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPlaylistTracks,
              [playlistId],
              {#limit: limit},
            ),
            returnValue: _i5.Future<List<_i2.Track>>.value(<_i2.Track>[]),
          )
          as _i5.Future<List<_i2.Track>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getBrowseCategories({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBrowseCategories, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getCategoryPlaylists(
    String? categoryId, {
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCategoryPlaylists,
              [categoryId],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<_i2.Track>> getPopularTracks({int? limit = 12}) =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTracks, [], {#limit: limit}),
            returnValue: _i5.Future<List<_i2.Track>>.value(<_i2.Track>[]),
          )
          as _i5.Future<List<_i2.Track>>);

  @override
  _i5.Future<List<String>> getAvailableMarkets() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableMarkets, []),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getRelatedArtists(String? artistId) =>
      (super.noSuchMethod(
            Invocation.method(#getRelatedArtists, [artistId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<String>> getAvailableGenreSeeds() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableGenreSeeds, []),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);
}
