include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - lib/core/playback/packages/**

linter:
  rules:
    avoid_print: false
    use_null_aware_elements: false
    curly_braces_in_flow_control_structures: false
    unnecessary_string_escapes: false
