import json
import os
import glob

# Dictionary of translations generated by the AI
translations = {
    'ar': {
        "songsTab": "الأغاني", "foldersTab": "المجلدات", "artistsTab": "الفنانين", "albumsTab": "الألبومات",
        "addMusic": "إضافة موسيقى", "addFiles": "إضافة ملفات", "addFolder": "إضافة مجلد", "rescanLibrary": "إعادة فحص المكتبة",
        "sortTitle": "الترتيب حسب العنوان", "sortArtist": "الترتيب حسب الفنان", "sortAlbum": "الترتيب حسب الألبوم",
        "sortDuration": "الترتيب حسب المدة", "sortDateAdded": "الترتيب حسب تاريخ الإضافة", "trackInformation": "معلومات المسار",
        "removeFromLibrary": "إزالة من المكتبة", "showInFolder": "عرض في المجلد", "unknownArtist": "فنان غير معروف",
        "unknownAlbum": "ألبوم غير معروف", "importedFiles": "الملفات المستوردة", "playFolder": "تشغيل المجلد",
        "shuffleFolder": "تشغيل المجلد عشوائياً", "playAll": "تشغيل الكل", "includeSubfolders": "تضمين المجلدات الفرعية",
        "noLocalSongs": "لم يتم العثور على أغانٍ محلية", "searchLocalMusic": "البحث في الموسيقى المحلية...",
        "viewAsList": "عرض كقائمة", "viewAsGrid": "عرض كشبكة", "trackInfoPath": "المسار", "trackInfoFormat": "التنسيق",
        "trackInfoDuration": "المدة", "trackCount": "{count, plural, =0{0 مقطع} =1{مقطع واحد} =2{مقطعان} few{{count} مقاطع} many{{count} مقطعًا} other{{count} مقطع}}"
    },
    'bn': {
        "songsTab": "গান", "foldersTab": "ফোল্ডার", "artistsTab": "শিল্পী", "albumsTab": "অ্যালবাম",
        "addMusic": "মিউজিক যোগ করুন", "addFiles": "ফাইল যোগ করুন", "addFolder": "ফোল্ডার যোগ করুন", "rescanLibrary": "লাইব্রেরি আবার স্ক্যান করুন",
        "sortTitle": "শিরোনাম অনুযায়ী সাজান", "sortArtist": "শিল্পী অনুযায়ী সাজান", "sortAlbum": "অ্যালবাম অনুযায়ী সাজান",
        "sortDuration": "সময়কাল অনুযায়ী সাজান", "sortDateAdded": "যোগ করার তারিখ অনুযায়ী সাজান", "trackInformation": "ট্র্যাকের তথ্য",
        "removeFromLibrary": "লাইব্রেরি থেকে সরান", "showInFolder": "ফোল্ডারে দেখান", "unknownArtist": "অজানা শিল্পী",
        "unknownAlbum": "অজানা অ্যালবাম", "importedFiles": "আমদানিকৃত ফাইল", "playFolder": "ফোল্ডার চালান",
        "shuffleFolder": "ফোল্ডার শাফেল করুন", "playAll": "সব চালান", "includeSubfolders": "সাবফোল্ডার অন্তর্ভুক্ত করুন",
        "noLocalSongs": "কোনো লোকাল গান পাওয়া যায়নি", "searchLocalMusic": "লোকাল মিউজিক খুঁজুন...",
        "viewAsList": "তালিকা হিসেবে দেখুন", "viewAsGrid": "গ্রিড হিসেবে দেখুন", "trackInfoPath": "পথ", "trackInfoFormat": "ফরম্যাট",
        "trackInfoDuration": "সময়কাল", "trackCount": "{count, plural, =0{0 ট্র্যাক} =1{1 ট্র্যাক} other{{count} ট্র্যাক}}"
    },
    'cs': {
        "songsTab": "Skladby", "foldersTab": "Složky", "artistsTab": "Umělci", "albumsTab": "Alba",
        "addMusic": "Přidat hudbu", "addFiles": "Přidat soubory", "addFolder": "Přidat složku", "rescanLibrary": "Znovu skenovat knihovnu",
        "sortTitle": "Seřadit podle názvu", "sortArtist": "Seřadit podle umělce", "sortAlbum": "Seřadit podle alba",
        "sortDuration": "Seřadit podle délky", "sortDateAdded": "Seřadit podle data přidání", "trackInformation": "Informace o skladbě",
        "removeFromLibrary": "Odebrat z knihovny", "showInFolder": "Zobrazit ve složce", "unknownArtist": "Neznámý umělec",
        "unknownAlbum": "Neznámé album", "importedFiles": "Importované soubory", "playFolder": "Přehrát složku",
        "shuffleFolder": "Náhodně přehrát složku", "playAll": "Přehrát vše", "includeSubfolders": "Zahrnout podsložky",
        "noLocalSongs": "Nenalezeny žádné místní skladby", "searchLocalMusic": "Hledat místní hudbu...",
        "viewAsList": "Zobrazit jako seznam", "viewAsGrid": "Zobrazit jako mřížku", "trackInfoPath": "Cesta", "trackInfoFormat": "Formát",
        "trackInfoDuration": "Délka", "trackCount": "{count, plural, =0{0 skladeb} =1{1 skladba} few{{count} skladby} other{{count} skladeb}}"
    },
    'da': {
        "songsTab": "Sange", "foldersTab": "Mapper", "artistsTab": "Kunstnere", "albumsTab": "Album",
        "addMusic": "Tilføj musik", "addFiles": "Tilføj filer", "addFolder": "Tilføj mappe", "rescanLibrary": "Genskan bibliotek",
        "sortTitle": "Sortér efter titel", "sortArtist": "Sortér efter kunstner", "sortAlbum": "Sortér efter album",
        "sortDuration": "Sortér efter varighed", "sortDateAdded": "Sortér efter tilføjelsesdato", "trackInformation": "Sporinformation",
        "removeFromLibrary": "Fjern fra bibliotek", "showInFolder": "Vis i mappe", "unknownArtist": "Ukendt kunstner",
        "unknownAlbum": "Ukendt album", "importedFiles": "Importerede filer", "playFolder": "Afspil mappe",
        "shuffleFolder": "Bland mappe", "playAll": "Afspil alle", "includeSubfolders": "Inkluder undermapper",
        "noLocalSongs": "Ingen lokale sange fundet", "searchLocalMusic": "Søg i lokal musik...",
        "viewAsList": "Vis som liste", "viewAsGrid": "Vis som gitter", "trackInfoPath": "Sti", "trackInfoFormat": "Format",
        "trackInfoDuration": "Varighed", "trackCount": "{count, plural, =0{0 spor} =1{1 spor} other{{count} spor}}"
    },
    'de': {
        "songsTab": "Lieder", "foldersTab": "Ordner", "artistsTab": "Künstler", "albumsTab": "Alben",
        "addMusic": "Musik hinzufügen", "addFiles": "Dateien hinzufügen", "addFolder": "Ordner hinzufügen", "rescanLibrary": "Bibliothek neu scannen",
        "sortTitle": "Nach Titel sortieren", "sortArtist": "Nach Künstler sortieren", "sortAlbum": "Nach Album sortieren",
        "sortDuration": "Nach Dauer sortieren", "sortDateAdded": "Nach Hinzufügedatum sortieren", "trackInformation": "Titelinformationen",
        "removeFromLibrary": "Aus Bibliothek entfernen", "showInFolder": "Im Ordner anzeigen", "unknownArtist": "Unbekannter Künstler",
        "unknownAlbum": "Unbekanntes Album", "importedFiles": "Importierte Dateien", "playFolder": "Ordner abspielen",
        "shuffleFolder": "Ordner zufällig abspielen", "playAll": "Alle abspielen", "includeSubfolders": "Unterordner einschließen",
        "noLocalSongs": "Keine lokalen Lieder gefunden", "searchLocalMusic": "Lokale Musik suchen...",
        "viewAsList": "Als Liste anzeigen", "viewAsGrid": "Als Raster anzeigen", "trackInfoPath": "Pfad", "trackInfoFormat": "Format",
        "trackInfoDuration": "Dauer", "trackCount": "{count, plural, =0{0 Titel} =1{1 Titel} other{{count} Titel}}"
    },
    'es': {
        "songsTab": "Canciones", "foldersTab": "Carpetas", "artistsTab": "Artistas", "albumsTab": "Álbumes",
        "addMusic": "Añadir música", "addFiles": "Añadir archivos", "addFolder": "Añadir carpeta", "rescanLibrary": "Volver a escanear biblioteca",
        "sortTitle": "Ordenar por título", "sortArtist": "Ordenar por artista", "sortAlbum": "Ordenar por álbum",
        "sortDuration": "Ordenar por duración", "sortDateAdded": "Ordenar por fecha", "trackInformation": "Información de la pista",
        "removeFromLibrary": "Eliminar de la biblioteca", "showInFolder": "Mostrar en carpeta", "unknownArtist": "Artista desconocido",
        "unknownAlbum": "Álbum desconocido", "importedFiles": "Archivos importados", "playFolder": "Reproducir carpeta",
        "shuffleFolder": "Reproducir carpeta en orden aleatorio", "playAll": "Reproducir todo", "includeSubfolders": "Incluir subcarpetas",
        "noLocalSongs": "No se encontraron canciones locales", "searchLocalMusic": "Buscar música local...",
        "viewAsList": "Ver como lista", "viewAsGrid": "Ver como cuadrícula", "trackInfoPath": "Ruta", "trackInfoFormat": "Formato",
        "trackInfoDuration": "Duración", "trackCount": "{count, plural, =0{0 pistas} =1{1 pista} other{{count} pistas}}"
    },
    'et': {
        "songsTab": "Laulud", "foldersTab": "Kaustad", "artistsTab": "Artistid", "albumsTab": "Albumid",
        "addMusic": "Lisa muusika", "addFiles": "Lisa failid", "addFolder": "Lisa kaust", "rescanLibrary": "Skanni teek uuesti",
        "sortTitle": "Sordi pealkirja järgi", "sortArtist": "Sordi artisti järgi", "sortAlbum": "Sordi albumi järgi",
        "sortDuration": "Sordi kestuse järgi", "sortDateAdded": "Sordi lisamiskuupäeva järgi", "trackInformation": "Loo teave",
        "removeFromLibrary": "Eemalda teegist", "showInFolder": "Näita kaustas", "unknownArtist": "Tundmatu artist",
        "unknownAlbum": "Tundmatu album", "importedFiles": "Imporditud failid", "playFolder": "Esita kausta",
        "shuffleFolder": "Esita kausta juhuslikult", "playAll": "Esita kõik", "includeSubfolders": "Kaasa alamkaustad",
        "noLocalSongs": "Kohalikke laule ei leitud", "searchLocalMusic": "Otsi kohalikku muusikat...",
        "viewAsList": "Vaata loendina", "viewAsGrid": "Vaata ruudustikuna", "trackInfoPath": "Tee", "trackInfoFormat": "Vorming",
        "trackInfoDuration": "Kestus", "trackCount": "{count, plural, =0{0 lugu} =1{1 lugu} other{{count} lugu}}"
    },
    'fa': {
        "songsTab": "آهنگ‌ها", "foldersTab": "پوشه‌ها", "artistsTab": "هنرمندان", "albumsTab": "آلبوم‌ها",
        "addMusic": "افزودن موسیقی", "addFiles": "افزودن فایل‌ها", "addFolder": "افزودن پوشه", "rescanLibrary": "اسکن مجدد کتابخانه",
        "sortTitle": "مرتب‌سازی بر اساس عنوان", "sortArtist": "مرتب‌سازی بر اساس هنرمند", "sortAlbum": "مرتب‌سازی بر اساس آلبوم",
        "sortDuration": "مرتب‌سازی بر اساس مدت زمان", "sortDateAdded": "مرتب‌سازی بر اساس تاریخ افزودن", "trackInformation": "اطلاعات آهنگ",
        "removeFromLibrary": "حذف از کتابخانه", "showInFolder": "نمایش در پوشه", "unknownArtist": "هنرمند ناشناس",
        "unknownAlbum": "آلبوم ناشناس", "importedFiles": "فایل‌های وارد شده", "playFolder": "پخش پوشه",
        "shuffleFolder": "پخش تصادفی پوشه", "playAll": "پخش همه", "includeSubfolders": "شامل زیرپوشه‌ها",
        "noLocalSongs": "هیچ آهنگ محلی یافت نشد", "searchLocalMusic": "جستجوی موسیقی محلی...",
        "viewAsList": "نمایش به صورت لیست", "viewAsGrid": "نمایش به صورت شبکه", "trackInfoPath": "مسیر", "trackInfoFormat": "فرمت",
        "trackInfoDuration": "مدت زمان", "trackCount": "{count, plural, =0{0 قطعه} =1{1 قطعه} other{{count} قطعه}}"
    },
    'fil': {
        "songsTab": "Mga Kanta", "foldersTab": "Mga Folder", "artistsTab": "Mga Artista", "albumsTab": "Mga Album",
        "addMusic": "Magdagdag ng Musika", "addFiles": "Magdagdag ng mga File", "addFolder": "Magdagdag ng Folder", "rescanLibrary": "I-scan Muli ang Library",
        "sortTitle": "Pagbukud-bukurin ayon sa Pamagat", "sortArtist": "Pagbukud-bukurin ayon sa Artista", "sortAlbum": "Pagbukud-bukurin ayon sa Album",
        "sortDuration": "Pagbukud-bukurin ayon sa Tagal", "sortDateAdded": "Pagbukud-bukurin ayon sa Petsa", "trackInformation": "Impormasyon ng Track",
        "removeFromLibrary": "Alisin mula sa Library", "showInFolder": "Ipakita sa Folder", "unknownArtist": "Hindi Kilalang Artista",
        "unknownAlbum": "Hindi Kilalang Album", "importedFiles": "Mga Na-import na File", "playFolder": "I-play ang Folder",
        "shuffleFolder": "I-shuffle ang Folder", "playAll": "I-play Lahat", "includeSubfolders": "Isama ang mga Subfolder",
        "noLocalSongs": "Walang nahanap na mga lokal na kanta", "searchLocalMusic": "Maghanap ng lokal na musika...",
        "viewAsList": "Tingnan bilang Listahan", "viewAsGrid": "Tingnan bilang Grid", "trackInfoPath": "Path", "trackInfoFormat": "Format",
        "trackInfoDuration": "Tagal", "trackCount": "{count, plural, =0{0 track} =1{1 track} other{{count} track}}"
    },
    'fr': {
        "songsTab": "Chansons", "foldersTab": "Dossiers", "artistsTab": "Artistes", "albumsTab": "Albums",
        "addMusic": "Ajouter de la musique", "addFiles": "Ajouter des fichiers", "addFolder": "Ajouter un dossier", "rescanLibrary": "Réanalyser la bibliothèque",
        "sortTitle": "Trier par titre", "sortArtist": "Trier par artiste", "sortAlbum": "Trier par album",
        "sortDuration": "Trier par durée", "sortDateAdded": "Trier par date d'ajout", "trackInformation": "Informations sur la piste",
        "removeFromLibrary": "Supprimer de la bibliothèque", "showInFolder": "Afficher dans le dossier", "unknownArtist": "Artiste inconnu",
        "unknownAlbum": "Album inconnu", "importedFiles": "Fichiers importés", "playFolder": "Lire le dossier",
        "shuffleFolder": "Lecture aléatoire du dossier", "playAll": "Tout lire", "includeSubfolders": "Inclure les sous-dossiers",
        "noLocalSongs": "Aucune chanson locale trouvée", "searchLocalMusic": "Rechercher de la musique locale...",
        "viewAsList": "Afficher en liste", "viewAsGrid": "Afficher en grille", "trackInfoPath": "Chemin", "trackInfoFormat": "Format",
        "trackInfoDuration": "Durée", "trackCount": "{count, plural, =0{0 piste} =1{1 piste} other{{count} pistes}}"
    },
    'gn': {
        "songsTab": "Purahéi", "foldersTab": "Mba'eryru", "artistsTab": "Puraheihára", "albumsTab": "Aty",
        "addMusic": "Mbojuaju purahéi", "addFiles": "Mbojuaju marandukuéra", "addFolder": "Mbojuaju mba'eryru", "rescanLibrary": "Heka jey purahéi",
        "sortTitle": "Oñemohenda héra rupi", "sortArtist": "Oñemohenda puraheihára rupi", "sortAlbum": "Oñemohenda aty rupi",
        "sortDuration": "Oñemohenda pukukue rupi", "sortDateAdded": "Oñemohenda ára rupi", "trackInformation": "Purahéi marandu",
        "removeFromLibrary": "Nohẽ purahéi atýgui", "showInFolder": "Hechauka mba'eryrúpe", "unknownArtist": "Puraheihára ojekuaa'ỹva",
        "unknownAlbum": "Aty ojekuaa'ỹva", "importedFiles": "Marandukuéra oñemoguahẽva", "playFolder": "Mbohyapu mba'eryru",
        "shuffleFolder": "Mbohyapu sarambi mba'eryru", "playAll": "Mbohyapu paite", "includeSubfolders": "Mbojuaju mba'eryru'i",
        "noLocalSongs": "Ndojejuhúi purahéi ko'ápe", "searchLocalMusic": "Heka purahéi ko'ápe...",
        "viewAsList": "Hechauka tysýi ramo", "viewAsGrid": "Hechauka ñanduti ramo", "trackInfoPath": "Tape", "trackInfoFormat": "Ysaja",
        "trackInfoDuration": "Pukukue", "trackCount": "{count, plural, =0{0 purahéi} =1{1 purahéi} other{{count} purahéi}}"
    },
    'hi': {
        "songsTab": "गाने", "foldersTab": "फ़ोल्डर", "artistsTab": "कलाकार", "albumsTab": "एल्बम",
        "addMusic": "संगीत जोड़ें", "addFiles": "फ़ाइलें जोड़ें", "addFolder": "फ़ोल्डर जोड़ें", "rescanLibrary": "लाइब्रेरी को फिर से स्कैन करें",
        "sortTitle": "शीर्षक के अनुसार क्रमित करें", "sortArtist": "कलाकार के अनुसार क्रमित करें", "sortAlbum": "एल्बम के अनुसार क्रमित करें",
        "sortDuration": "अवधि के अनुसार क्रमित करें", "sortDateAdded": "जोड़ने की तिथि के अनुसार क्रमित करें", "trackInformation": "ट्रैक की जानकारी",
        "removeFromLibrary": "लाइब्रेरी से हटाएं", "showInFolder": "फ़ोल्डर में दिखाएं", "unknownArtist": "अज्ञात कलाकार",
        "unknownAlbum": "अज्ञात एल्बम", "importedFiles": "आयातित फ़ाइलें", "playFolder": "फ़ोल्डर चलाएं",
        "shuffleFolder": "फ़ोल्डर शफ़ल करें", "playAll": "सभी चलाएं", "includeSubfolders": "उपफ़ोल्डर शामिल करें",
        "noLocalSongs": "कोई स्थानीय गाने नहीं मिले", "searchLocalMusic": "स्थानीय संगीत खोजें...",
        "viewAsList": "सूची के रूप में देखें", "viewAsGrid": "ग्रिड के रूप में देखें", "trackInfoPath": "पथ", "trackInfoFormat": "प्रारूप",
        "trackInfoDuration": "अवधि", "trackCount": "{count, plural, =0{0 ट्रैक} =1{1 ट्रैक} other{{count} ट्रैक}}"
    },
    'hr': {
        "songsTab": "Pjesme", "foldersTab": "Mape", "artistsTab": "Izvođači", "albumsTab": "Albumi",
        "addMusic": "Dodaj glazbu", "addFiles": "Dodaj datoteke", "addFolder": "Dodaj mapu", "rescanLibrary": "Ponovno skeniraj fonoteku",
        "sortTitle": "Sortiraj po naslovu", "sortArtist": "Sortiraj po izvođaču", "sortAlbum": "Sortiraj po albumu",
        "sortDuration": "Sortiraj po trajanju", "sortDateAdded": "Sortiraj po datumu dodavanja", "trackInformation": "Informacije o zapisu",
        "removeFromLibrary": "Ukloni iz fonoteke", "showInFolder": "Prikaži u mapi", "unknownArtist": "Nepoznat izvođač",
        "unknownAlbum": "Nepoznat album", "importedFiles": "Uvezene datoteke", "playFolder": "Reproduciraj mapu",
        "shuffleFolder": "Nasumično reproduciraj mapu", "playAll": "Reproduciraj sve", "includeSubfolders": "Uključi podmape",
        "noLocalSongs": "Nema lokalnih pjesama", "searchLocalMusic": "Pretraži lokalnu glazbu...",
        "viewAsList": "Prikaži kao popis", "viewAsGrid": "Prikaži kao mrežu", "trackInfoPath": "Put", "trackInfoFormat": "Format",
        "trackInfoDuration": "Trajanje", "trackCount": "{count, plural, =0{0 zapisa} =1{1 zapis} few{{count} zapisa} other{{count} zapisa}}"
    },
    'hu': {
        "songsTab": "Dalok", "foldersTab": "Mappák", "artistsTab": "Előadók", "albumsTab": "Albumok",
        "addMusic": "Zene hozzáadása", "addFiles": "Fájlok hozzáadása", "addFolder": "Mappa hozzáadása", "rescanLibrary": "Könyvtár újraolvasása",
        "sortTitle": "Rendezés cím szerint", "sortArtist": "Rendezés előadó szerint", "sortAlbum": "Rendezés album szerint",
        "sortDuration": "Rendezés időtartam szerint", "sortDateAdded": "Rendezés hozzáadás dátuma szerint", "trackInformation": "Szám információi",
        "removeFromLibrary": "Eltávolítás a könyvtárból", "showInFolder": "Megjelenítés mappában", "unknownArtist": "Ismeretlen előadó",
        "unknownAlbum": "Ismeretlen album", "importedFiles": "Importált fájlok", "playFolder": "Mappa lejátszása",
        "shuffleFolder": "Mappa keverése", "playAll": "Összes lejátszása", "includeSubfolders": "Almappák belefoglalása",
        "noLocalSongs": "Nem találhatók helyi dalok", "searchLocalMusic": "Helyi zene keresése...",
        "viewAsList": "Megjelenítés listaként", "viewAsGrid": "Megjelenítés rácsként", "trackInfoPath": "Útvonal", "trackInfoFormat": "Formátum",
        "trackInfoDuration": "Időtartam", "trackCount": "{count, plural, =0{0 szám} =1{1 szám} other{{count} szám}}"
    },
    'id': {
        "songsTab": "Lagu", "foldersTab": "Folder", "artistsTab": "Artis", "albumsTab": "Album",
        "addMusic": "Tambahkan Musik", "addFiles": "Tambahkan File", "addFolder": "Tambahkan Folder", "rescanLibrary": "Pindai Ulang Pustaka",
        "sortTitle": "Urutkan berdasarkan Judul", "sortArtist": "Urutkan berdasarkan Artis", "sortAlbum": "Urutkan berdasarkan Album",
        "sortDuration": "Urutkan berdasarkan Durasi", "sortDateAdded": "Urutkan berdasarkan Tanggal", "trackInformation": "Informasi Trek",
        "removeFromLibrary": "Hapus dari Pustaka", "showInFolder": "Tampilkan di Folder", "unknownArtist": "Artis Tidak Dikenal",
        "unknownAlbum": "Album Tidak Dikenal", "importedFiles": "File yang Diimpor", "playFolder": "Putar Folder",
        "shuffleFolder": "Acak Folder", "playAll": "Putar Semua", "includeSubfolders": "Sertakan Subfolder",
        "noLocalSongs": "Tidak ada lagu lokal yang ditemukan", "searchLocalMusic": "Cari musik lokal...",
        "viewAsList": "Tampilkan sebagai Daftar", "viewAsGrid": "Tampilkan sebagai Grid", "trackInfoPath": "Jalur", "trackInfoFormat": "Format",
        "trackInfoDuration": "Durasi", "trackCount": "{count, plural, =0{0 trek} =1{1 trek} other{{count} trek}}"
    },
    'it': {
        "songsTab": "Brani", "foldersTab": "Cartelle", "artistsTab": "Artisti", "albumsTab": "Album",
        "addMusic": "Aggiungi musica", "addFiles": "Aggiungi file", "addFolder": "Aggiungi cartella", "rescanLibrary": "Riesamina libreria",
        "sortTitle": "Ordina per titolo", "sortArtist": "Ordina per artista", "sortAlbum": "Ordina per album",
        "sortDuration": "Ordina per durata", "sortDateAdded": "Ordina per data aggiunta", "trackInformation": "Informazioni brano",
        "removeFromLibrary": "Rimuovi dalla libreria", "showInFolder": "Mostra nella cartella", "unknownArtist": "Artista sconosciuto",
        "unknownAlbum": "Album sconosciuto", "importedFiles": "File importati", "playFolder": "Riproduci cartella",
        "shuffleFolder": "Riproduzione casuale cartella", "playAll": "Riproduci tutto", "includeSubfolders": "Includi sottocartelle",
        "noLocalSongs": "Nessun brano locale trovato", "searchLocalMusic": "Cerca musica locale...",
        "viewAsList": "Visualizza come elenco", "viewAsGrid": "Visualizza come griglia", "trackInfoPath": "Percorso", "trackInfoFormat": "Formato",
        "trackInfoDuration": "Durata", "trackCount": "{count, plural, =0{0 brani} =1{1 brano} other{{count} brani}}"
    },
    'ja': {
        "songsTab": "曲", "foldersTab": "フォルダ", "artistsTab": "アーティスト", "albumsTab": "アルバム",
        "addMusic": "音楽を追加", "addFiles": "ファイルを追加", "addFolder": "フォルダを追加", "rescanLibrary": "ライブラリを再スキャン",
        "sortTitle": "タイトル順", "sortArtist": "アーティスト順", "sortAlbum": "アルバム順",
        "sortDuration": "再生時間順", "sortDateAdded": "追加日順", "trackInformation": "トラック情報",
        "removeFromLibrary": "ライブラリから削除", "showInFolder": "フォルダに表示", "unknownArtist": "不明なアーティスト",
        "unknownAlbum": "不明なアルバム", "importedFiles": "インポートされたファイル", "playFolder": "フォルダを再生",
        "shuffleFolder": "フォルダをシャッフル", "playAll": "すべて再生", "includeSubfolders": "サブフォルダを含める",
        "noLocalSongs": "ローカルの曲が見つかりません", "searchLocalMusic": "ローカルの音楽を検索...",
        "viewAsList": "リスト表示", "viewAsGrid": "グリッド表示", "trackInfoPath": "パス", "trackInfoFormat": "フォーマット",
        "trackInfoDuration": "再生時間", "trackCount": "{count, plural, =0{0 トラック} =1{1 トラック} other{{count} トラック}}"
    },
    'ka': {
        "songsTab": "სიმღერები", "foldersTab": "საქაღალდეები", "artistsTab": "შემსრულებლები", "albumsTab": "ალბომები",
        "addMusic": "მუსიკის დამატება", "addFiles": "ფაილების დამატება", "addFolder": "საქაღალდის დამატება", "rescanLibrary": "ბიბლიოთეკის ხელახლა სკანირება",
        "sortTitle": "დალაგება სათაურის მიხედვით", "sortArtist": "დალაგება შემსრულებლის მიხედვით", "sortAlbum": "დალაგება ალბომის მიხედვით",
        "sortDuration": "დალაგება ხანგრძლივობის მიხედვით", "sortDateAdded": "დალაგება დამატების თარიღის მიხედვით", "trackInformation": "ტრეკის ინფორმაცია",
        "removeFromLibrary": "ბიბლიოთეკიდან ამოღება", "showInFolder": "საქაღალდეში ჩვენება", "unknownArtist": "უცნობი შემსრულებელი",
        "unknownAlbum": "უცნობი ალბომი", "importedFiles": "იმპორტირებული ფაილები", "playFolder": "საქაღალდის დაკვრა",
        "shuffleFolder": "საქაღალდის შემთხვევითი დაკვრა", "playAll": "ყველას დაკვრა", "includeSubfolders": "ქვესაქაღალდეების ჩართვა",
        "noLocalSongs": "ლოკალური სიმღერები ვერ მოიძებნა", "searchLocalMusic": "ლოკალური მუსიკის ძიება...",
        "viewAsList": "სიის სახით ნახვა", "viewAsGrid": "ბადის სახით ნახვა", "trackInfoPath": "გზა", "trackInfoFormat": "ფორმატი",
        "trackInfoDuration": "ხანგრძლივობა", "trackCount": "{count, plural, =0{0 ტრეკი} =1{1 ტრეკი} other{{count} ტრეკი}}"
    },
    'kk': {
        "songsTab": "Өлеңдер", "foldersTab": "Қалталар", "artistsTab": "Орындаушылар", "albumsTab": "Альбомдар",
        "addMusic": "Музыка қосу", "addFiles": "Файлдарды қосу", "addFolder": "Қалтаны қосу", "rescanLibrary": "Кітапхананы қайта сканерлеу",
        "sortTitle": "Атауы бойынша сұрыптау", "sortArtist": "Орындаушы бойынша сұрыптау", "sortAlbum": "Альбом бойынша сұрыптау",
        "sortDuration": "Ұзақтығы бойынша сұрыптау", "sortDateAdded": "Қосылған күні бойынша сұрыптау", "trackInformation": "Трек ақпараты",
        "removeFromLibrary": "Кітапханадан өшіру", "showInFolder": "Қалтада көрсету", "unknownArtist": "Белгісіз орындаушы",
        "unknownAlbum": "Белгісіз альбом", "importedFiles": "Импортталған файлдар", "playFolder": "Қалтаны ойнату",
        "shuffleFolder": "Қалтаны араластыру", "playAll": "Барлығын ойнату", "includeSubfolders": "Ішкі қалталарды қосу",
        "noLocalSongs": "Жергілікті әндер табылмады", "searchLocalMusic": "Жергілікті музыканы іздеу...",
        "viewAsList": "Тізім ретінде қарау", "viewAsGrid": "Тор ретінде қарау", "trackInfoPath": "Жол", "trackInfoFormat": "Пішім",
        "trackInfoDuration": "Ұзақтығы", "trackCount": "{count, plural, =0{0 трек} =1{1 трек} other{{count} трек}}"
    },
    'ko': {
        "songsTab": "곡", "foldersTab": "폴더", "artistsTab": "아티스트", "albumsTab": "앨범",
        "addMusic": "음악 추가", "addFiles": "파일 추가", "addFolder": "폴더 추가", "rescanLibrary": "라이브러리 재검색",
        "sortTitle": "제목순으로 정렬", "sortArtist": "아티스트순으로 정렬", "sortAlbum": "앨범순으로 정렬",
        "sortDuration": "시간순으로 정렬", "sortDateAdded": "추가된 날짜순으로 정렬", "trackInformation": "트랙 정보",
        "removeFromLibrary": "라이브러리에서 제거", "showInFolder": "폴더에 표시", "unknownArtist": "알 수 없는 아티스트",
        "unknownAlbum": "알 수 없는 앨범", "importedFiles": "가져온 파일", "playFolder": "폴더 재생",
        "shuffleFolder": "폴더 셔플 재생", "playAll": "모두 재생", "includeSubfolders": "하위 폴더 포함",
        "noLocalSongs": "로컬 곡을 찾을 수 없습니다", "searchLocalMusic": "로컬 음악 검색...",
        "viewAsList": "목록으로 보기", "viewAsGrid": "그리드로 보기", "trackInfoPath": "경로", "trackInfoFormat": "형식",
        "trackInfoDuration": "시간", "trackCount": "{count, plural, =0{0 트랙} =1{1 트랙} other{{count} 트랙}}"
    },
    'lv': {
        "songsTab": "Dziesmas", "foldersTab": "Mapes", "artistsTab": "Mākslinieki", "albumsTab": "Albumi",
        "addMusic": "Pievienot mūziku", "addFiles": "Pievienot failus", "addFolder": "Pievienot mapi", "rescanLibrary": "Atkārtoti skenēt bibliotēku",
        "sortTitle": "Kārtot pēc nosaukuma", "sortArtist": "Kārtot pēc mākslinieka", "sortAlbum": "Kārtot pēc albuma",
        "sortDuration": "Kārtot pēc ilguma", "sortDateAdded": "Kārtot pēc pievienošanas datuma", "trackInformation": "Sliežu ceļa informācija",
        "removeFromLibrary": "Noņemt no bibliotēkas", "showInFolder": "Rādīt mapē", "unknownArtist": "Nezināms mākslinieks",
        "unknownAlbum": "Nezināms albums", "importedFiles": "Importētie faili", "playFolder": "Atskaņot mapi",
        "shuffleFolder": "Jaukt mapi", "playAll": "Atskaņot visu", "includeSubfolders": "Iekļaut apakšmapes",
        "noLocalSongs": "Vietējās dziesmas nav atrastas", "searchLocalMusic": "Meklēt vietējo mūziku...",
        "viewAsList": "Skatīt kā sarakstu", "viewAsGrid": "Skatīt kā režģi", "trackInfoPath": "Ceļš", "trackInfoFormat": "Formāts",
        "trackInfoDuration": "Ilgums", "trackCount": "{count, plural, =0{0 celiņi} =1{1 celiņš} other{{count} celiņi}}"
    },
    'ms': {
        "songsTab": "Lagu", "foldersTab": "Folder", "artistsTab": "Artis", "albumsTab": "Album",
        "addMusic": "Tambah Muzik", "addFiles": "Tambah Fail", "addFolder": "Tambah Folder", "rescanLibrary": "Imbas Semula Pustaka",
        "sortTitle": "Isih mengikut Tajuk", "sortArtist": "Isih mengikut Artis", "sortAlbum": "Isih mengikut Album",
        "sortDuration": "Isih mengikut Tempoh", "sortDateAdded": "Isih mengikut Tarikh", "trackInformation": "Maklumat Trek",
        "removeFromLibrary": "Alih Keluar daripada Pustaka", "showInFolder": "Tunjukkan dalam Folder", "unknownArtist": "Artis Tidak Diketahui",
        "unknownAlbum": "Album Tidak Diketahui", "importedFiles": "Fail yang Diimport", "playFolder": "Main Folder",
        "shuffleFolder": "Kocok Folder", "playAll": "Main Semua", "includeSubfolders": "Sertakan Subfolder",
        "noLocalSongs": "Tiada lagu tempatan ditemui", "searchLocalMusic": "Cari muzik tempatan...",
        "viewAsList": "Lihat sebagai Senarai", "viewAsGrid": "Lihat sebagai Grid", "trackInfoPath": "Laluan", "trackInfoFormat": "Format",
        "trackInfoDuration": "Tempoh", "trackCount": "{count, plural, =0{0 trek} =1{1 trek} other{{count} trek}}"
    },
    'my': {
        "songsTab": "သီချင်းများ", "foldersTab": "ဖိုင်တွဲများ", "artistsTab": "အနုပညာရှင်များ", "albumsTab": "အယ်လ်ဘမ်များ",
        "addMusic": "တေးဂီတ ပေါင်းထည့်ရန်", "addFiles": "ဖိုင်များ ပေါင်းထည့်ရန်", "addFolder": "ဖိုင်တွဲ ပေါင်းထည့်ရန်", "rescanLibrary": "ဒစ်ဂျစ်တယ် စာကြည့်တိုက်ကို ပြန်လည်စကင်ဖတ်ရန်",
        "sortTitle": "ခေါင်းစဉ်အလိုက် စီရန်", "sortArtist": "အနုပညာရှင်အလိုက် စီရန်", "sortAlbum": "အယ်လ်ဘမ်အလိုက် စီရန်",
        "sortDuration": "ကြာချိန်အလိုက် စီရန်", "sortDateAdded": "ပေါင်းထည့်သည့်ရက်စွဲအလိုက် စီရန်", "trackInformation": "တေးသွား အချက်အလက်",
        "removeFromLibrary": "ဒစ်ဂျစ်တယ် စာကြည့်တိုက်မှ ဖယ်ရှားရန်", "showInFolder": "ဖိုင်တွဲတွင် ပြရန်", "unknownArtist": "အမည်မသိ အနုပညာရှင်",
        "unknownAlbum": "အမည်မသိ အယ်လ်ဘမ်", "importedFiles": "တင်သွင်းထားသော ဖိုင်များ", "playFolder": "ဖိုင်တွဲ ဖွင့်ရန်",
        "shuffleFolder": "ဖိုင်တွဲ ရောမွှေရန်", "playAll": "အားလုံး ဖွင့်ရန်", "includeSubfolders": "ဖိုင်တွဲခွဲများ ပါဝင်ရန်",
        "noLocalSongs": "ဒေသန္တရ သီချင်းများ မတွေ့ပါ", "searchLocalMusic": "ဒေသန္တရ တေးဂီတကို ရှာရန်...",
        "viewAsList": "စာရင်းအဖြစ် ကြည့်ရန်", "viewAsGrid": "ဇယားကွက်အဖြစ် ကြည့်ရန်", "trackInfoPath": "လမ်းကြောင်း", "trackInfoFormat": "ဖော်မတ်",
        "trackInfoDuration": "ကြာချိန်", "trackCount": "{count, plural, =0{0 တေးသွား} =1{1 တေးသွား} other{{count} တေးသွား}}"
    },
    'pcm': {
        "songsTab": "Songs", "foldersTab": "Folders", "artistsTab": "Artists", "albumsTab": "Albums",
        "addMusic": "Add Music", "addFiles": "Add Files", "addFolder": "Add Folder", "rescanLibrary": "Rescan Library",
        "sortTitle": "Sort by Title", "sortArtist": "Sort by Artist", "sortAlbum": "Sort by Album",
        "sortDuration": "Sort by Duration", "sortDateAdded": "Sort by Date", "trackInformation": "Track Information",
        "removeFromLibrary": "Remove from Library", "showInFolder": "Show in Folder", "unknownArtist": "Unknown Artist",
        "unknownAlbum": "Unknown Album", "importedFiles": "Imported Files", "playFolder": "Play Folder",
        "shuffleFolder": "Shuffle Folder", "playAll": "Play All", "includeSubfolders": "Include Subfolders",
        "noLocalSongs": "No local songs found", "searchLocalMusic": "Search local music...",
        "viewAsList": "View as List", "viewAsGrid": "View as Grid", "trackInfoPath": "Path", "trackInfoFormat": "Format",
        "trackInfoDuration": "Duration", "trackCount": "{count, plural, =0{0 tracks} =1{1 track} other{{count} tracks}}"
    },
    'pl': {
        "songsTab": "Utwory", "foldersTab": "Foldery", "artistsTab": "Wykonawcy", "albumsTab": "Albumy",
        "addMusic": "Dodaj muzykę", "addFiles": "Dodaj pliki", "addFolder": "Dodaj folder", "rescanLibrary": "Skanuj bibliotekę",
        "sortTitle": "Sortuj według tytułu", "sortArtist": "Sortuj według wykonawcy", "sortAlbum": "Sortuj według albumu",
        "sortDuration": "Sortuj według czasu", "sortDateAdded": "Sortuj według daty dodania", "trackInformation": "Informacje o utworze",
        "removeFromLibrary": "Usuń z biblioteki", "showInFolder": "Pokaż w folderze", "unknownArtist": "Nieznany wykonawca",
        "unknownAlbum": "Nieznany album", "importedFiles": "Zaimportowane pliki", "playFolder": "Odtwórz folder",
        "shuffleFolder": "Odtwarzaj folder losowo", "playAll": "Odtwórz wszystko", "includeSubfolders": "Uwzględnij podfoldery",
        "noLocalSongs": "Nie znaleziono lokalnych utworów", "searchLocalMusic": "Szukaj lokalnej muzyki...",
        "viewAsList": "Widok listy", "viewAsGrid": "Widok siatki", "trackInfoPath": "Ścieżka", "trackInfoFormat": "Format",
        "trackInfoDuration": "Czas trwania", "trackCount": "{count, plural, =0{0 utworów} =1{1 utwór} few{{count} utwory} other{{count} utworów}}"
    },
    'pt': {
        "songsTab": "Músicas", "foldersTab": "Pastas", "artistsTab": "Artistas", "albumsTab": "Álbuns",
        "addMusic": "Adicionar música", "addFiles": "Adicionar arquivos", "addFolder": "Adicionar pasta", "rescanLibrary": "Reescanear biblioteca",
        "sortTitle": "Ordenar por título", "sortArtist": "Ordenar por artista", "sortAlbum": "Ordenar por álbum",
        "sortDuration": "Ordenar por duração", "sortDateAdded": "Ordenar por data de adição", "trackInformation": "Informações da faixa",
        "removeFromLibrary": "Remover da biblioteca", "showInFolder": "Mostrar na pasta", "unknownArtist": "Artista desconhecido",
        "unknownAlbum": "Álbum desconhecido", "importedFiles": "Arquivos importados", "playFolder": "Reproduzir pasta",
        "shuffleFolder": "Misturar pasta", "playAll": "Reproduzir tudo", "includeSubfolders": "Incluir subpastas",
        "noLocalSongs": "Nenhuma música local encontrada", "searchLocalMusic": "Procurar música local...",
        "viewAsList": "Ver como lista", "viewAsGrid": "Ver como grade", "trackInfoPath": "Caminho", "trackInfoFormat": "Formato",
        "trackInfoDuration": "Duração", "trackCount": "{count, plural, =0{0 faixas} =1{1 faixa} other{{count} faixas}}"
    },
    'ru': {
        "songsTab": "Песни", "foldersTab": "Папки", "artistsTab": "Исполнители", "albumsTab": "Альбомы",
        "addMusic": "Добавить музыку", "addFiles": "Добавить файлы", "addFolder": "Добавить папку", "rescanLibrary": "Пересканировать медиатеку",
        "sortTitle": "Сортировать по названию", "sortArtist": "Сортировать по исполнителю", "sortAlbum": "Сортировать по альбому",
        "sortDuration": "Сортировать по длительности", "sortDateAdded": "Сортировать по дате добавления", "trackInformation": "Информация о треке",
        "removeFromLibrary": "Удалить из медиатеки", "showInFolder": "Показать в папке", "unknownArtist": "Неизвестный исполнитель",
        "unknownAlbum": "Неизвестный альбом", "importedFiles": "Импортированные файлы", "playFolder": "Воспроизвести папку",
        "shuffleFolder": "Перемешать папку", "playAll": "Воспроизвести все", "includeSubfolders": "Включая вложенные папки",
        "noLocalSongs": "Локальные песни не найдены", "searchLocalMusic": "Поиск локальной музыки...",
        "viewAsList": "В виде списка", "viewAsGrid": "В виде сетки", "trackInfoPath": "Путь", "trackInfoFormat": "Формат",
        "trackInfoDuration": "Длительность", "trackCount": "{count, plural, =0{0 треков} =1{1 трек} few{{count} трека} many{{count} треков} other{{count} трека}}"
    },
    'sv': {
        "songsTab": "Låtar", "foldersTab": "Mappar", "artistsTab": "Artister", "albumsTab": "Album",
        "addMusic": "Lägg till musik", "addFiles": "Lägg till filer", "addFolder": "Lägg till mapp", "rescanLibrary": "Skanna om bibliotek",
        "sortTitle": "Sortera efter titel", "sortArtist": "Sortera efter artist", "sortAlbum": "Sortera efter album",
        "sortDuration": "Sortera efter längd", "sortDateAdded": "Sortera efter datum", "trackInformation": "Spårinformation",
        "removeFromLibrary": "Ta bort från bibliotek", "showInFolder": "Visa i mapp", "unknownArtist": "Okänd artist",
        "unknownAlbum": "Okänt album", "importedFiles": "Importerade filer", "playFolder": "Spela upp mapp",
        "shuffleFolder": "Blanda mapp", "playAll": "Spela upp alla", "includeSubfolders": "Inkludera undermappar",
        "noLocalSongs": "Inga lokala låtar hittades", "searchLocalMusic": "Sök lokal musik...",
        "viewAsList": "Visa som lista", "viewAsGrid": "Visa som rutnät", "trackInfoPath": "Sökväg", "trackInfoFormat": "Format",
        "trackInfoDuration": "Längd", "trackCount": "{count, plural, =0{0 spår} =1{1 spår} other{{count} spår}}"
    },
    'uz': {
        "songsTab": "Qo'shiqlar", "foldersTab": "Jildlar", "artistsTab": "Ijrochilar", "albumsTab": "Albomlar",
        "addMusic": "Musiqa qo'shish", "addFiles": "Fayllar qo'shish", "addFolder": "Jild qo'shish", "rescanLibrary": "Kutubxonani qayta skanerlash",
        "sortTitle": "Nomi bo'yicha saralash", "sortArtist": "Ijrochi bo'yicha saralash", "sortAlbum": "Albom bo'yicha saralash",
        "sortDuration": "Davomiyligi bo'yicha saralash", "sortDateAdded": "Qo'shilgan sana bo'yicha saralash", "trackInformation": "Trek haqida ma'lumot",
        "removeFromLibrary": "Kutubxonadan olib tashlash", "showInFolder": "Jildda ko'rsatish", "unknownArtist": "Noma'lum ijrochi",
        "unknownAlbum": "Noma'lum albom", "importedFiles": "Import qilingan fayllar", "playFolder": "Jildni o'ynatish",
        "shuffleFolder": "Jildni aralashtirib o'ynatish", "playAll": "Barchasini o'ynatish", "includeSubfolders": "Ostki jildlarni qo'shish",
        "noLocalSongs": "Hech qanday mahalliy qo'shiq topilmadi", "searchLocalMusic": "Mahalliy musiqani qidirish...",
        "viewAsList": "Ro'yxat sifatida ko'rish", "viewAsGrid": "To'r sifatida ko'rish", "trackInfoPath": "Yo'l", "trackInfoFormat": "Format",
        "trackInfoDuration": "Davomiyligi", "trackCount": "{count, plural, =0{0 trek} =1{1 trek} other{{count} trek}}"
    },
    'zh': {
        "songsTab": "歌曲", "foldersTab": "文件夹", "artistsTab": "艺术家", "albumsTab": "专辑",
        "addMusic": "添加音乐", "addFiles": "添加文件", "addFolder": "添加文件夹", "rescanLibrary": "重新扫描库",
        "sortTitle": "按标题排序", "sortArtist": "按艺术家排序", "sortAlbum": "按专辑排序",
        "sortDuration": "按时长排序", "sortDateAdded": "按添加日期排序", "trackInformation": "曲目信息",
        "removeFromLibrary": "从库中移除", "showInFolder": "在文件夹中显示", "unknownArtist": "未知艺术家",
        "unknownAlbum": "未知专辑", "importedFiles": "导入的文件", "playFolder": "播放文件夹",
        "shuffleFolder": "随机播放文件夹", "playAll": "播放全部", "includeSubfolders": "包含子文件夹",
        "noLocalSongs": "未找到本地歌曲", "searchLocalMusic": "搜索本地音乐...",
        "viewAsList": "列表视图", "viewAsGrid": "网格视图", "trackInfoPath": "路径", "trackInfoFormat": "格式",
        "trackInfoDuration": "时长", "trackCount": "{count, plural, =0{0 首曲目} =1{1 首曲目} other{{count} 首曲目}}"
    }
}

# The meta for all these new keys, to satisfy strict IDE linter
meta_blocks = {}
for k in translations['es'].keys():
    if k == "trackCount":
        meta_blocks["@" + k] = {"placeholders": {"count": {}}}
    else:
        meta_blocks["@" + k] = {}
        
# Inject translations and metadata into every arb file
for filepath in glob.glob('lib/l10n/app_*.arb'):
    filename = os.path.basename(filepath)
    lang_code = filename.replace('app_', '').replace('.arb', '')
    
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    t = translations.get(lang_code)
    
    if t:
        # It's one of the 30 non-english langs
        for k, v in t.items():
            data[k] = v
    else:
        # Just in case, fallback to en keys but translated ones are only for the 30 languages
        pass

    # Inject metadata for everything missing
    keys = list(data.keys())
    for k in keys:
        if not k.startswith('@'):
            meta_key = f"@{k}"
            if meta_key not in data:
                if k == "trackCount":
                    data[meta_key] = {"placeholders": {"count": {}}}
                elif k == "versionInfo":
                    data[meta_key] = {"placeholders": {"version": {}, "build": {}}}
                elif k == "copyright":
                    data[meta_key] = {"placeholders": {"year": {}}}
                elif k in ["titleSubtitle"]:
                    data[meta_key] = {"placeholders": {"title": {}, "subtitle": {}}}
                elif k in ["featuringArtist"]:
                    data[meta_key] = {"placeholders": {"artistName": {}}}
                elif k in ["currentCountry"]:
                    data[meta_key] = {"placeholders": {"country": {}}}
                elif k in ["errorDescription", "errorTitle"]:
                    data[meta_key] = {"placeholders": {"err": {}, "error": {}}}
                elif k in ["artistItems"]:
                    data[meta_key] = {"placeholders": {"artist": {}}}
                elif k in ["genreItems"]:
                    data[meta_key] = {"placeholders": {"genre": {}}}
                elif k in ["titleItems", "nameItems"]:
                    data[meta_key] = {"placeholders": {"name": {}}}
                elif k in ["minutes", "seconds"]:
                    data[meta_key] = {"placeholders": {"minutes": {}, "seconds": {}}}
                else:
                    data[meta_key] = {}
                    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

print("Bulk translation complete!")
