import json
import os
import glob

# Dictionary of translations generated by the AI for the remaining languages
translations = {
    'hr': {
        "songsTab": "Pjesme", "foldersTab": "Mape", "artistsTab": "Izvođači", "albumsTab": "Albumi",
        "addMusic": "Dodaj glazbu", "addFiles": "Dodaj datoteke", "addFolder": "Dodaj mapu", "rescanLibrary": "Ponovno skeniraj biblioteku",
        "sortTitle": "Poredaj po naslovu", "sortArtist": "Poredaj po izvođaču", "sortAlbum": "Poredaj po albumu",
        "sortDuration": "Poredaj po trajanju", "sortDateAdded": "Poredaj po datumu", "trackInformation": "Informacije o zapisu",
        "removeFromLibrary": "Ukloni iz biblioteke", "showInFolder": "Prikaži u mapi", "unknownArtist": "Nepoznat izvođač",
        "unknownAlbum": "Nepoznat album", "importedFiles": "Uvezene datoteke", "playFolder": "Pokreni mapu",
        "shuffleFolder": "Nasumično pokreni mapu", "playAll": "Pokreni sve", "includeSubfolders": "Uključi podmape",
        "noLocalSongs": "Nema lokalnih pjesama", "searchLocalMusic": "Pretraži lokalnu glazbu...",
        "viewAsList": "Prikaži kao popis", "viewAsGrid": "Prikaži kao mrežu", "trackInfoPath": "Putanja", "trackInfoFormat": "Format",
        "trackInfoDuration": "Trajanje", "trackCount": "{count, plural, =0{0 zapisa} =1{1 zapis} few{{count} zapisa} other{{count} zapisa}}"
    },
    'ja': {
        "songsTab": "曲", "foldersTab": "フォルダ", "artistsTab": "アーティスト", "albumsTab": "アルバム",
        "addMusic": "音楽を追加", "addFiles": "ファイルを追加", "addFolder": "フォルダを追加", "rescanLibrary": "ライブラリを再スキャン",
        "sortTitle": "タイトル順", "sortArtist": "アーティスト順", "sortAlbum": "アルバム順",
        "sortDuration": "再生時間順", "sortDateAdded": "追加日順", "trackInformation": "トラック情報",
        "removeFromLibrary": "ライブラリから削除", "showInFolder": "フォルダに表示", "unknownArtist": "不明なアーティスト",
        "unknownAlbum": "不明なアルバム", "importedFiles": "インポートされたファイル", "playFolder": "フォルダを再生",
        "shuffleFolder": "フォルダをシャッフル", "playAll": "すべて再生", "includeSubfolders": "サブフォルダを含める",
        "noLocalSongs": "ローカルの曲が見つかりません", "searchLocalMusic": "ローカルの音楽を検索...",
        "viewAsList": "リスト表示", "viewAsGrid": "グリッド表示", "trackInfoPath": "パス", "trackInfoFormat": "フォーマット",
        "trackInfoDuration": "再生時間", "trackCount": "{count, plural, =0{0 トラック} =1{1 トラック} other{{count} トラック}}"
    },
    'ko': {
        "songsTab": "곡", "foldersTab": "폴더", "artistsTab": "아티스트", "albumsTab": "앨범",
        "addMusic": "음악 추가", "addFiles": "파일 추가", "addFolder": "폴더 추가", "rescanLibrary": "라이브러리 재검색",
        "sortTitle": "제목순으로 정렬", "sortArtist": "아티스트순으로 정렬", "sortAlbum": "앨범순으로 정렬",
        "sortDuration": "시간순으로 정렬", "sortDateAdded": "추가된 날짜순으로 정렬", "trackInformation": "트랙 정보",
        "removeFromLibrary": "라이브러리에서 제거", "showInFolder": "폴더에 표시", "unknownArtist": "알 수 없는 아티스트",
        "unknownAlbum": "알 수 없는 앨범", "importedFiles": "가져온 파일", "playFolder": "폴더 재생",
        "shuffleFolder": "폴더 셔플 재생", "playAll": "모두 재생", "includeSubfolders": "하위 폴더 포함",
        "noLocalSongs": "로컬 곡을 찾을 수 없습니다", "searchLocalMusic": "로컬 음악 검색...",
        "viewAsList": "목록으로 보기", "viewAsGrid": "그리드로 보기", "trackInfoPath": "경로", "trackInfoFormat": "형식",
        "trackInfoDuration": "시간", "trackCount": "{count, plural, =0{0 트랙} =1{1 트랙} other{{count} 트랙}}"
    }
}

for filepath in glob.glob('lib/l10n/app_*.arb'):
    filename = os.path.basename(filepath)
    lang_code = filename.replace('app_', '').replace('.arb', '')
    
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    t = translations.get(lang_code)
    
    if t:
        for k, v in t.items():
            data[k] = v
            
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

print("Second bulk translation complete!")
