// Mocks generated by Mockito 5.4.6 from annotations
// in ppplayer/test/features/player/queue_export_ui_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ppplayer/core/local_library/audio_format_registry.dart' as _i5;
import 'package:ppplayer/core/local_library/local_library_service.dart' as _i2;
import 'package:ppplayer/core/local_library/m3u_handler.dart' as _i6;
import 'package:ppplayer/core/models/track.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LocalLibraryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalLibraryService extends _i1.Mock
    implements _i2.LocalLibraryService {
  MockLocalLibraryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Track>> importFiles() =>
      (super.noSuchMethod(
            Invocation.method(#importFiles, []),
            returnValue: _i3.Future<List<_i4.Track>>.value(<_i4.Track>[]),
          )
          as _i3.Future<List<_i4.Track>>);

  @override
  _i3.Future<void> importVideoFiles() =>
      (super.noSuchMethod(
            Invocation.method(#importVideoFiles, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Track>> importFilesByPaths(
    List<String>? paths, {
    _i5.ImportMediaScope? scopeHint = _i5.ImportMediaScope.both,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFilesByPaths,
              [paths],
              {#scopeHint: scopeHint},
            ),
            returnValue: _i3.Future<List<_i4.Track>>.value(<_i4.Track>[]),
          )
          as _i3.Future<List<_i4.Track>>);

  @override
  _i3.Future<void> importFolder() =>
      (super.noSuchMethod(
            Invocation.method(#importFolder, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> importVideoFolder() =>
      (super.noSuchMethod(
            Invocation.method(#importVideoFolder, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> importPlaylist({void Function(String?)? onProgress}) =>
      (super.noSuchMethod(
            Invocation.method(#importPlaylist, [], {#onProgress: onProgress}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> processPlaylistFile(
    String? filePath,
    String? fileName, {
    void Function(String?)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processPlaylistFile,
              [filePath, fileName],
              {#onProgress: onProgress},
            ),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<_i6.M3uExportResult?> exportPlaylist(int? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#exportPlaylist, [playlistId]),
            returnValue: _i3.Future<_i6.M3uExportResult?>.value(),
          )
          as _i3.Future<_i6.M3uExportResult?>);

  @override
  _i3.Future<_i6.M3uExportResult?> exportQueue(List<_i4.Track>? queueTracks) =>
      (super.noSuchMethod(
            Invocation.method(#exportQueue, [queueTracks]),
            returnValue: _i3.Future<_i6.M3uExportResult?>.value(),
          )
          as _i3.Future<_i6.M3uExportResult?>);

  @override
  _i3.Future<void> rescanLibrary({void Function(String?)? onProgress}) =>
      (super.noSuchMethod(
            Invocation.method(#rescanLibrary, [], {#onProgress: onProgress}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
